//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public int ID { get; set; }
        public Nullable<int> DanceId { get; set; }
        public Nullable<int> TrainerId { get; set; }
        public Nullable<int> CountStudent { get; set; }
    
        public virtual Coach Coach { get; set; }
        public virtual Dance Dance { get; set; }
        public virtual Student Student { get; set; }
    }
}
